#!/bin/bash
# Block edits to platform-generated files.
# Enforces: Critical rule 1 — never edit declarations/, B.d.ts, scriptlibrary.d.ts, Globals.d.ts.
#
# These files are generated by the platform and replaced on the next `b6p pull`, so a hand edit
# is lost. Until it is, the code type-checks against a declaration the platform will never
# produce, which is worse than a plain compile error.

HOOK_NAME="block-generated-files"
# ${BASH_SOURCE[0]%/*} rather than $(dirname ...): no external command, so this still works
# when PATH is empty. And a failed source is fatal — without the helper the checks below would
# all see an empty value, match nothing, and exit 0, which is the fail-open bug again.
source "${BASH_SOURCE[0]%/*}/lib/hook-input.sh" || {
  echo "BLOCKED: the BlueStep guardrail hook could not load its input helper (${BASH_SOURCE[0]%/*}/lib/hook-input.sh), so it cannot check this call. Reinstall or update the bluestep-tools plugin." >&2
  exit 2
}
hook_require_parse

FILE=$(hook_field_path file_path path)

if [[ "$FILE" == *"/declarations/"* ]] \
   || [[ "$FILE" == *"B.d.ts" ]] \
   || [[ "$FILE" == *"scriptlibrary.d.ts" ]] \
   || [[ "$FILE" == *"Globals.d.ts" ]]; then
  echo "BLOCKED: '$FILE' is platform-generated and gets replaced on the next pull, so this edit would be lost. If a declaration is wrong or missing, fix it on the platform — usually by adding the query or form-field import there — then run: b6p pull \"<DAV URL>\"" >&2
  exit 2
fi

exit 0
